Repository mash-up-kr/VitaminC_server, pull requests merged in 2024-06, with the labels that each got.

#1 Feat/prisma
  .example.env
  .gitignore
  README.md
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/main.ts
  src/prisma/client.ts
  src/prisma/migrations/20240613061302_init/migration.sql
  src/prisma/migrations/migration_lock.toml
  src/prisma/prisma.service.ts
  src/prisma/schema.prisma
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: enhancement

#6 Feat/swc: 컴파일러 swc로 변경
  nest-cli.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#4 Feat: Set up git hooks: Git hooks 적용했어요
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
  package.json
  pnpm-lock.yaml
Labels: enhancement

#5 Feat/auth: kakao sign in, auth 관련 guard 등 개발했어요
  .example.env
  .prettierrc
  README.md
  additional.d.ts
  nest-cli.json
  package.json
  pnpm-lock.yaml
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/kakao.strategy.ts
  src/common/constant/role.constant.ts
  src/common/decorators/auth-guard.decorator.ts
  src/common/decorators/id.decorator.ts
  src/common/decorators/user.decorator.ts
  src/common/guards/kakao.guard.ts
  src/common/guards/passport-auth.guard.ts
  src/main.ts
  src/prisma/migrations/20240617102040_role_added_to_user/migration.sql
  src/prisma/migrations/20240619041726_divide_user_provider/migration.sql
  src/prisma/schema.prisma
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#7 Feat/mikro orm: Prisma 삭제, Mikro ORM 적용
  .example.env
  README.md
  additional.d.ts
  docker-compose.yml
  package.json
  pnpm-lock.yaml
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/common/constant/role.constant.ts
  src/common/decorators/auth-guard.decorator.ts
  src/common/guards/passport-auth.guard.ts
  src/common/helper/extended-repository.helper.ts
  src/common/helper/mock.helper.ts
  src/main.ts
  src/migrations/.snapshot-postgres.json
  src/migrations/Migration20240621085648.ts
  src/mikro-orm.config.ts
  src/prisma/client.ts
  src/prisma/migrations/20240613061302_init/migration.sql
  src/prisma/migrations/20240617102040_role_added_to_user/migration.sql
  src/prisma/migrations/20240619041726_divide_user_provider/migration.sql
  src/prisma/migrations/migration_lock.toml
  src/prisma/prisma.service.ts
  src/prisma/schema.prisma
  src/users/dtos/create-user.dto.ts
  src/users/dtos/update-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/entities/user.type.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  tsconfig.json
Labels: feature

#9 Feat/env validation: env validation 만들었어요
  additional.d.ts
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/common/helper/env.helper.ts
  src/common/helper/env.validation.ts
Labels: feature

#10 Chore/plural-to-singular: 모듈 이름 복수형에서 단수형으로 변경
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/strategies/jwt.strategy.ts
  src/common/decorators/auth-guard.decorator.ts
  src/common/guards/passport-auth.guard.ts
  src/user/dtos/create-user.dto.ts
  src/user/dtos/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/entities/user.type.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.repository.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  src/users/users.controller.spec.ts
  src/users/users.module.ts
Labels: chore

#8 Feat/ Create pr template: PR 템플릿 만들었다.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feature

#11 Feat/db-base-setting: user, map 중간 테이블 생성
  src/app.module.ts
  src/map/dtos/create-map.dto.ts
  src/map/dtos/update-map.dto.ts
  src/map/entities/map.entity.ts
  src/map/map.controller.spec.ts
  src/map/map.controller.ts
  src/map/map.module.ts
  src/map/map.repository.ts
  src/map/map.service.spec.ts
  src/map/map.service.ts
  src/migrations/.snapshot-postgres.json
  src/migrations/Migration20240624105844.ts
  src/user-map/dtos/create-user-map.dto.ts
  src/user-map/dtos/update-user-map.dto.ts
  src/user-map/entities/user-map.entity.ts
  src/user-map/user-map.module.ts
  src/user-map/user-map.repository.ts
  src/user-map/user-map.service.spec.ts
  src/user-map/user-map.service.ts
  src/user/entities/user.entity.ts
Labels: feature

#16 Feat/change sign in logic 카카오 로그인 로직을 바꿨어요
  .example.env
  additional.d.ts
  package.json
  pnpm-lock.yaml
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/strategies/kakao.strategy.ts
  src/common/decorators/id.decorator.ts
  src/common/decorators/kakao-info.decorator.ts
  src/common/helper/env.validation.ts
  src/migrations/.snapshot-postgres.json
  src/migrations/Migration20240625055046.ts
  src/user/dtos/create-user.dto.ts
  src/user/dtos/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.service.ts
Labels: feature

#26 Feat: create map, get map, get all map 구현
  src/entities/user-map.entity.ts
  src/map/dtos/map-item-for-user.dto.ts
  src/map/dtos/map-response.dto.ts
  src/map/dtos/update-map.dto.ts
  src/map/map.controller.ts
  src/map/map.module.ts
  src/map/map.service.ts
  src/migrations/.snapshot-korrk-stage.json
  src/migrations/Migration20240629143458.ts
Labels: feature

#27 Feat/gpt 나쁜말 고르는 로직 썼다. gpt 써ㅅ서
  .example.env
  additional.d.ts
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/common/helper/env.validation.ts
  src/gpt/gpt.controller.ts
  src/gpt/gpt.module.ts
  src/gpt/gpt.service.ts
Labels: feature

#30 Feat: place, place-for-map, like, comment 관련 로직
  src/app.module.ts
  src/entities/index.ts
  src/entities/kakao-place.entity.ts
  src/entities/place-for-map.entity.ts
  src/entities/place-for-map.repository.ts
  src/entities/place.entity.ts
  src/entities/place.repository.ts
  src/migrations/.snapshot-korrk-stage.json
  src/migrations/Migration20240629185552.ts
  src/place/place.controller.ts
  src/place/place.module.ts
  src/place/place.service.ts
  src/search/search.module.ts
  src/search/search.service.ts
Labels: feature

#31 Feat/sentry 에러 처리 했당
  .example.env
  .gitignore
  README.md
  additional.d.ts
  package.json
  pnpm-lock.yaml
  src/app.controller.ts
  src/app.module.ts
  src/common/helper/env.validation.ts
  src/core/exception-filters/custom-exception.filter.ts
  src/main.ts
  src/mikro-orm.config.ts
  src/search/search.module.ts
  src/search/search.service.ts
  src/util/util.module.ts
  src/util/util.service.ts
  src/utils/index.ts
  tsconfig.json
Labels: feature
